# docker-compose.yml
version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env.development
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Codespacesがターミナルを接続できるように、コンテナを起動したまま待機させます
    command: sleep infinity
    volumes:
      - ./backend:/myapp
    ports:
      - "3001:3001"
    env_file:
      - ./.env.development
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    # 起動ロジックはentrypoint.shに任せます
    entrypoint: ["./entrypoint.sh"]
    ports:
      - "3000:3000"
    env_file:
      - ./.env.development
    depends_on:
      - web

volumes:
  db_data:
